export const dataBase = [
    {
        id: 1,
        image: "../ava.svg",
        recommendations: "85% пациентов",
        reviews: "83 отзыва",
        specialist: "Психолог",
        specialistName: "Сакович Екатерина Андреевна",
        experience: "Стаж 12 лет",
        doctorCategory: "Врач первой категории",
        receptionType: "в клинике",
        price: "5500 ₽",
        phone: "89650033900",
        type: "Телефон для записи",
        appointmentDoctor: 5,
        appointmentCalendar: "четверг, 3",
        buttonWatch: "19:30",
        appointmentCalendar2: "пятница, 4",
        buttonWatch2: "12:30",
        appointmentCalendar3: "суббота, 5",
        buttonWatch3: "14:15",
        address: "г. Москва, Ильменский пр., д. 10",
        metro1: "Кропоткинская",
        distance1: "550 м",
        metro2: "Арбатская",
        distance2: "940 м",
        metro3: "Смоленская",
        distance3: "820 м",



    },
    {
        id: 2,
        image: "../ava.svg",
        recommendations: "78% пациентов",
        reviews: "23 отзыва",
        specialist: "Психолог",
        specialistName: "Иванов Иван Андреевич",
        experience: "Стаж 1 лет",
        doctorCategory: "Врач третьей категории",
        receptionType: "в клинике",
        price: "1500 ₽",
        phone: "89650045566",
        type: "Телефон для записи",
        appointmentDoctor: 5,
        appointmentCalendar: "вторник, 20",
        buttonWatch: "19:30",
        appointmentCalendar2: "среда, 21",
        buttonWatch2: "12:30",
        appointmentCalendar3: "четверг, 22",
        buttonWatch3: "14:15",
        address: "г. Казань, Ильменский пр., д. 10",
        metro1: "Пушкинская",
        distance1: "550 м",
        metro2: "Арбатская",
        distance2: "940 м",
        metro3: "Смоленская",
        distance3: "820 м",



    }
]